// Bu dosya setup.py tarafından otomatik oluşturuldu. Elle düzenlemeyin.
// Generated by setup.py — do not edit manually.
var DERGI_CONFIG = {
  "title": "Turna",
  "totalPages": 44,
  "pageWidth": 972,
  "pageHeight": 1296,
  "imgPath": "pages/mobile/",
  "thumbPath": "pages/thumb/",
  "tocItems": [
    {
      "title": "Kapak",
      "page": 1
    }
  ]
};
