#!/usr/bin/env python3
"""
E-Dergi Kurulum Aracı
=====================
PDF dosyasını sayfa görüntülerine dönüştürür ve yapılandırmayı yazar.

Gereksinim:
    pip install pymupdf

Kullanım:
    python setup.py <pdf_dosyasi>
    python setup.py dergi.pdf
    python setup.py dergi.pdf --title "Turna Dergisi - Eylül 2024"
    python setup.py dergi.pdf --scale 2.0
"""

import sys
import os
import json
import argparse
import time


def check_dependencies():
    """PyMuPDF yüklü mü kontrol et."""
    try:
        import fitz  # noqa: F401
        return True
    except ImportError:
        print("\n[HATA] PyMuPDF kütüphanesi bulunamadı.")
        print("       Yüklemek için şu komutu çalıştırın:\n")
        print("       pip install pymupdf\n")
        return False


def progress_bar(current, total, width=40):
    """Konsol ilerleme çubuğu."""
    pct   = current / total
    filled = int(width * pct)
    bar   = "█" * filled + "░" * (width - filled)
    return f"[{bar}] {current:3d}/{total}  ({int(pct * 100):3d}%)"


def convert_pdf(pdf_path, output_dir, thumb_dir, scale=1.5, thumb_scale=0.2, jpeg_quality=85):
    """
    PDF sayfalarını JPG görüntülere dönüştür.

    Args:
        pdf_path      : Kaynak PDF dosya yolu
        output_dir    : Tam boyut JPG'lerin kaydedileceği klasör
        thumb_dir     : Küçük resim JPG'lerinin kaydedileceği klasör
        scale         : Tam boyut için büyütme katsayısı (varsayılan 1.5)
        thumb_scale   : Küçük resim için büyütme katsayısı (varsayılan 0.2)
        jpeg_quality  : JPEG kalitesi 1-100 (varsayılan 85)

    Returns:
        dict: {totalPages, pageWidth, pageHeight}
    """
    import fitz

    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(thumb_dir,  exist_ok=True)

    doc = fitz.open(pdf_path)
    total = len(doc)

    first_page = doc[0]
    rect   = first_page.rect
    page_w = int(rect.width  * scale)
    page_h = int(rect.height * scale)

    print(f"\n  PDF dosyası  : {os.path.basename(pdf_path)}")
    print(f"  Toplam sayfa : {total}")
    print(f"  Sayfa boyutu : {page_w} × {page_h} px  (ölçek: {scale}×)")
    print(f"  Kalite       : JPEG %{jpeg_quality}")
    print(f"  Hedef klasör : {output_dir}/\n")

    start = time.time()

    for i in range(total):
        page = doc[i]

        # --- Tam boyut ---
        mat = fitz.Matrix(scale, scale)
        pix = page.get_pixmap(matrix=mat, alpha=False)
        pix.save(
            os.path.join(output_dir, f"{i + 1}.jpg"),
            jpg_quality=jpeg_quality,
        )

        # --- Küçük resim ---
        mat_t = fitz.Matrix(thumb_scale, thumb_scale)
        pix_t = page.get_pixmap(matrix=mat_t, alpha=False)
        pix_t.save(
            os.path.join(thumb_dir, f"{i + 1}.jpg"),
            jpg_quality=75,
        )

        print(f"\r  {progress_bar(i + 1, total)}", end="", flush=True)

    doc.close()
    elapsed = time.time() - start
    print(f"\n\n  Süre: {elapsed:.1f}s  ({elapsed / total:.2f}s / sayfa)")

    return {
        "totalPages": total,
        "pageWidth":  page_w,
        "pageHeight": page_h,
    }


def write_config(config_path, data):
    """
    Tarayıcının file:// protokolünde okuyabileceği JS yapılandırma dosyasını yazar.
    Bir <script src="dergi_config.js"> ile yüklenir — JSON.fetch() gerektirmez.
    """
    js = "// Bu dosya setup.py tarafından otomatik oluşturuldu. Elle düzenlemeyin.\n"
    js += "// Generated by setup.py — do not edit manually.\n"
    js += "var DERGI_CONFIG = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"

    with open(config_path, "w", encoding="utf-8") as f:
        f.write(js)

    print(f"  Yapılandırma : {config_path}")


def main():
    parser = argparse.ArgumentParser(
        description="PDF'i e-dergi görüntülerine dönüştürür.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("pdf", help="Kaynak PDF dosyası")
    parser.add_argument(
        "--title",
        default="E-Dergi",
        help='Dergi başlığı (varsayılan: "E-Dergi")',
    )
    parser.add_argument(
        "--scale",
        type=float,
        default=1.5,
        help="Tam boyut sayfa ölçeği (varsayılan: 1.5)",
    )
    parser.add_argument(
        "--quality",
        type=int,
        default=85,
        choices=range(50, 101),
        metavar="50-100",
        help="JPEG kalitesi (varsayılan: 85)",
    )
    parser.add_argument(
        "--out",
        default="pages",
        help='Çıktı klasörü (varsayılan: "pages")',
    )

    args = parser.parse_args()

    print("=" * 55)
    print("  E-Dergi Kurulum Aracı")
    print("=" * 55)

    if not check_dependencies():
        sys.exit(1)

    if not os.path.isfile(args.pdf):
        print(f"\n[HATA] Dosya bulunamadı: {args.pdf}\n")
        sys.exit(1)

    output_dir = os.path.join(args.out, "mobile")
    thumb_dir  = os.path.join(args.out, "thumb")

    info = convert_pdf(
        pdf_path      = args.pdf,
        output_dir    = output_dir,
        thumb_dir     = thumb_dir,
        scale         = args.scale,
        jpeg_quality  = args.quality,
    )

    config = {
        "title":      args.title,
        "totalPages": info["totalPages"],
        "pageWidth":  info["pageWidth"],
        "pageHeight": info["pageHeight"],
        "imgPath":    f"{args.out}/mobile/",
        "thumbPath":  f"{args.out}/thumb/",
        "tocItems":   [
            {"title": "Kapak", "page": 1}
        ],
    }
    print("\n  Not: dergi_config.js içindeki 'tocItems' dizisini")
    print("       kendi bölüm başlıklarınıza göre düzenleyin.")

    config_path = "dergi_config.js"
    write_config(config_path, config)

    print("\n" + "=" * 55)
    print("  Tamamlandı!")
    print("  index.html dosyasını tarayıcıda açabilirsiniz.")
    print("=" * 55 + "\n")


if __name__ == "__main__":
    main()
